package dbmlgorm

import (
	"fmt"
	"github.com/duythinht/dbml-go/core"
	"gopkg.in/yaml.v2"
	"log"
	"strings"
)

type Config struct {
	Package string
	Imports []string
	Types   []string
}

type Type struct {
	original string
	new      string
}

var headerTemplate = `// Auto-generated by dbml-to-gorm
// Do not edit by hand!
// Project: %v

package %v

`

func getProjectHeader(dbml *core.DBML) string {
	var config Config
	yamlBytes := []byte(dbml.Project.Note)
	err := yaml.Unmarshal(yamlBytes, &config)
	if err != nil {
		log.Fatal(err)
	}

	str := fmt.Sprintf(headerTemplate, dbml.Project.Name, config.Package)
	return str
}

func getProjectConfig(dbml *core.DBML) (string, map[string]string) {
	var config Config
	yamlBytes := []byte(dbml.Project.Note)
	err := yaml.Unmarshal(yamlBytes, &config)
	if err != nil {
		log.Fatal(err)
	}

	str := getProjectHeader(dbml)
	if len(config.Imports) > 0 {
		str += "import(\n"
		for _, imp := range config.Imports {
			str += "\t\"" + imp + "\"\n"
		}
		str += ")\n\n"
	}

	types := make(map[string]string)
	for _, t := range config.Types {
		splited := strings.Split(t, ":")
		types[splited[0]] = splited[1]
	}
	return str, types
}
